# This is a basic workflow to help you get started with Actions

name: Use PEM Secure File

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  use-pem:
    runs-on: ubuntu-latest

    steps:
    - name: Recreate .pem file
      run: |
        echo "${{ secrets.PRIVATE_KEY_PEM_B64 }}" | base64 -d > id_rsa.pem
        chmod 600 id_rsa.pem
        echo "PEM file recreated."

    - name: List files
      run: ls -la
