# This is a basic workflow to help you get started with Actions

name: Use Github secrets and variable

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # shows the secret var
  show-secrets-vars:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASSWORD }}
        APP_ENV: ${{ vars.ENV }}
        RETRIES: ${{ vars.RETRY_COUNT }}'
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show Secrets and Variables
        run: echo Hello, world! |
          echo "DB Username:$DB_USER"
          echo "DB Password:$DB_PASS"
          echo "Environment:$APP_ENV"
          echo "Retry Count:$RETRIES"
